apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: indichess
type: Opaque
stringData:
  root-password: root
  user-db-password: root
  match-db-password: root

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: indichess
type: Opaque
stringData:
  jwt-secret: change-me-change-me-change-me-change-me-32chars-min
