apiVersion: v1
kind: ConfigMap
metadata:
  name: match-service-config
  namespace: indichess
data:
  SPRING_APPLICATION_NAME: "match-service"
  SPRING_DATASOURCE_USERNAME: "root"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  USER_SERVICE_URL: "http://user-service:8081"
  JPA_DDL_AUTO: "validate"
