apiVersion: v1
kind: Secret
metadata:
  name: match-service-secret
  namespace: indichess
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: "jdbc:mysql://match-db:3306/match_service_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
  SPRING_DATASOURCE_PASSWORD: "root"
  JWT_SECRET: "change-me-change-me-change-me-change-me-32chars-min"
# Note: Replace the above values with your actual secrets in production
