apiVersion: v1
kind: Service
metadata:
  name: match-service
  namespace: indichess
  labels:
    app: match-service
spec:
  selector:
    app: match-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP
