apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: indichess
data:
  USER_SERVICE_URL: "http://user-service:8081"
  MATCH_SERVICE_URL: "http://match-service:8082"
  FRONTEND_URL: "http://localhost:3000"
  FRONTEND_URL_DEV: "http://localhost:5173"
