apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secret
  namespace: indichess
type: Opaque
stringData:
  JWT_SECRET: "change-me-change-me-change-me-change-me-32chars-min"
# Note: Use the same JWT secret across user-service, match-service, and api-gateway
